### ISSUE TITLE
Nginx conf is causing trouble

### ISSUE THREAD

**Issue by hapee** [sjacorg/bayanat#4] opened 2021-01-29 15:18 UTC
This part is causing the site not to work:

`location /static {
    alias /path/to/bayahat/enferno/static;
        expires max;
         }
`
If I adapt it and leave it there is causes permission denied issues, if I take it out the site is working but not saving anything.

What could be the cause of this?

Kind regards

**Comment by sjacgit** [comment] 2021-01-31 01:13
You need to change the path here to point to the static location in the setup path you have locally. For example, if you cloned the code into `/home/user/bayanat`, this line should look like: `location /static { alias /home/user/bayanat/enferno/static; expires max; }`. 

Additionally, there's an error in the readme and you need an extra `}` at the end of the NGINX conf file. Sorry about that! You can check the installation manual alongside the user guide on: https://docs.bayanat.org/en/install

**Comment by hapee** [comment] 2021-01-31 15:29
Thanks, I was aware of the changes you mentioned but I move bayanat to the /home/ directory and changed nginx setting which looks better now.

One thing that is puzzling me is the fact that I can for example locations like this:
![image](https://user-images.githubusercontent.com/379964/106389019-63515c80-63e1-11eb-92ab-24844f201294.png)
but when I reload the page they are gone, no errror in het log file:
![image](https://user-images.githubusercontent.com/379964/106389038-87ad3900-63e1-11eb-9e86-bae45b2f66a5.png)

**Comment by sjac-td** [comment] 2021-02-08 20:28
We're unable to reproduce this issue. Can you please have a look in the service log and check for errors when adding a location? You can use `journalctl -u bayanat.service`.

**Comment by sjacgit** [comment] 2021-02-08 20:30
We're unable to reproduce this issue. Can you please have a look in the service log and check for errors when adding a location? You can use `journalctl -u bayanat.service`.

**Comment by hapee** [comment] 2021-02-22 16:07
Thanks sjacgit, could this being empty also point you somewhere:

journalctl -u bayanat.service
-- Logs begin at Sun 2021-02-21 22:07:03 UTC, end at Mon 2021-02-22 16:06:15 UTC
-- No entries --
lines 1-2/2 (END)

**Comment by sjacgit** [comment] 2021-03-08 21:34
This probably means you chose a different name for the service. It's probably a good idea to reset the setup again using the latest code. The instructions are available on docs.bayanat.org.

**Comment by sjac-td** [comment] 2021-03-24 16:15
Hello again. The locations issue should now be fixed. Can you please check again after updating to the latest version and let us know if it's resolved?

**Comment by sjacgit** [comment] 2021-05-20 15:36
Hello again. Have you had a change to test this issue again in order for us to close it?

**Closed** 2021-05-25 09:12 UTC
